In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [ ]:
#Q.1
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (918, 11)
Shape of y: (918,)

In [6]:
X = pd.get_dummies(X, drop_first=True)

In [7]:
print(X.columns)
X.head()

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'Sex_M', 'ChestPainType_ATA', 'ChestPainType_NAP', 'ChestPainType_TA',
       'RestingECG_Normal', 'RestingECG_ST', 'ExerciseAngina_Y',
       'ST_Slope_Flat', 'ST_Slope_Up'],
      dtype='str')

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,True,False,True,False,True,False,False,False,True

In [8]:
#Q.2
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

In [10]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (734, 15)
X_test shape: (184, 15)
y_train shape: (734,)
y_test shape: (184,)

In [11]:
#Q.3
from sklearn.linear_model import LogisticRegression

In [12]:
model = LogisticRegression()

In [13]:
model.fit(X_train, y_train)

c:\Users\Shree\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [14]:
print("Logistic Regression model trained successfully.")

Logistic Regression model trained successfully.

In [15]:
#Q.4
y_pred = model.predict(X_test)

In [16]:
print("First 10 Actual Values:")
print(y_test.head(10).values)

print("\nFirst 10 Predicted Values:")
print(y_pred[:10])

First 10 Actual Values:
[0 1 1 1 0 1 1 0 1 1]

First 10 Predicted Values:
[0 0 1 1 0 1 1 0 1 1]

In [17]:
#Q.5
from sklearn.metrics import confusion_matrix

In [18]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[66 11]
 [16 91]]

In [19]:
tn, fp, fn, tp = cm.ravel()

print("True Negative (TN):", tn)
print("False Positive (FP):", fp)
print("False Negative (FN):", fn)
print("True Positive (TP):", tp)

True Negative (TN): 66
False Positive (FP): 11
False Negative (FN): 16
True Positive (TP): 91

In [20]:
#Q.6
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

In [21]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8532608695652174

In [22]:
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

Precision: 0.8921568627450981

In [23]:
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

Recall: 0.8504672897196262

In [24]:
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.8708133971291866

In [25]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.86      0.83        77
           1       0.89      0.85      0.87       107

    accuracy                           0.85       184
   macro avg       0.85      0.85      0.85       184
weighted avg       0.86      0.85      0.85       184

In [26]:
#Q.7
import joblib

In [27]:
joblib.dump(model, "heart_model.pkl")

['heart_model.pkl']

In [28]:
joblib.dump(X.columns.tolist(), "columns.pkl")

['columns.pkl']

In [30]:
print("Model and preprocessing objects saved successfully.")

Model and preprocessing objects saved successfully.

In [31]:
#Q.8
import joblib
import pandas as pd

model = joblib.load("heart_model.pkl")
columns = joblib.load("columns.pkl")

In [32]:
sample = pd.DataFrame({
    "Age": [52],
    "Sex": ["M"],
    "ChestPainType": ["ATA"],
    "RestingBP": [130],
    "Cholesterol": [250],
    "FastingBS": [0],
    "RestingECG": ["Normal"],
    "MaxHR": [150],
    "ExerciseAngina": ["N"],
    "Oldpeak": [1.2],
    "ST_Slope": ["Up"]
})

In [33]:
sample = pd.get_dummies(sample)
sample = sample.reindex(columns=columns, fill_value=0)

In [34]:
prediction = model.predict(sample)

if prediction[0] == 1:
    print("Prediction: Heart Disease Detected")
else:
    print("Prediction: No Heart Disease")

Prediction: No Heart Disease